[package]
name = "mtl"
version = "0.3.7"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]

[lib]
name = "mtl"
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
debug = 1
panic = "abort"
overflow-checks = true
lto = true
opt-level = 's'

[dependencies]
backtrace = "0.3"
bincode = "1.0"
byteorder = "1.1"
chrono = "0.4"
combine = "3.2"
failure = "0.1.1"
fern = "0.5"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
pcx = "0.2"
scopeguard = "1.0"
serde = "1.0.15"
serde_derive = "1.0.15"
smallvec = "0.6"
thread_local = "0.3.5"
vec_map = "0.8.0"

[dependencies.winapi]
version = "0.3"
features = ["heapapi", "libloaderapi", "processthreadsapi", "winuser"]

[dependencies.samase_shim]
git = "https://github.com/neivv/samase_plugin"

[dependencies.bw_dat]
git = "https://github.com/neivv/aise"

[dependencies.whack]
git = "https://github.com/neivv/whack/"
