[package]
name = "mtl"
version = "0.3.35"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
edition = "2018"

[lib]
name = "mtl"
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"
lto = "no"
opt-level = 1
codegen-units = 4

[profile.release]
debug = 1
panic = "abort"
overflow-checks = true
lto = true
opt-level = 's'

[dependencies]
anyhow = "1.0"
arrayvec = "0.5"
bincode = "1.0"
byteorder = "1.1"
chrono = "0.4"
fern = "=0.5.8"
json = "0.12"
lazy_static = "1.0"
libc = "0.2"
log = "0.4"
mpq = "=0.7.0"
pcx = "0.2"
rand = "0.7"
scopeguard = "1.1"
serde = "1.0.15"
serde_derive = "1.0.15"
smallvec = "1.0"
thread_local = "1.0"
vec_map = "0.8.0"

[dependencies.winapi]
version = "0.3"
features = ["heapapi", "libloaderapi", "processthreadsapi", "winuser"]

[dependencies.samase_shim]
git = "https://github.com/neivv/samase_plugin"
rev = "efea4458c610128a949728464b8099222bcadcdc"

[dependencies.bw_dat]
git = "https://github.com/neivv/aise"
rev = "65395000aaf3104ebc9b1b34ed80138265b69735"

[dependencies.whack]
git = "https://github.com/neivv/whack/"
rev = "e8e847864c2938735040ca3c68ef1cf9e03b692f"

[dependencies.rand_xorshift]
version = "0.2.0"
features = ["serde1"]

[build-dependencies]
scopeguard = "1.1"

[build-dependencies.winapi]
version = "0.3"
features = ["d3dcompiler"]
